name: poker_manager
description: Poker Manager - Group Poker Game Organizer
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cached_network_image: ^3.4.1
  flutter:
    sdk: flutter
  flutter_contacts: ^1.1.9+2
  flutter_svg: ^2.0.10+1
  flutter_riverpod: ^3.1.0
  freezed_annotation: ^3.1.0
  go_router: ^17.0.1
  image_picker: ^1.0.7
  intl: ^0.20.2
  json_annotation: ^4.8.1
  supabase_flutter: ^2.3.4
  url_launcher: ^6.2.0
  uuid: ^4.5.2
  package_info_plus: ^9.0.0

dev_dependencies:
  build_runner: ^2.4.8
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.2.3
  json_serializable: ^6.7.1
  supabase: ^2.0.8
  test: ^1.24.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icons/app_icon.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#2E7D32"
  adaptive_icon_foreground: "assets/icons/app_icon_foreground.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/img_app_logo.svg
    - env.json
